- name: copy rsyslog configuration
  ansible.builtin.template:
    src: backend.conf
    dest: /etc/rsyslog.d/backend.conf

- name: restart rsyslog
  ansible.builtin.systemd_service:
    name: rsyslog
    state: restarted
