- name: Get Secrets
  hosts: localhost
  tasks:
    - name: create common secret SSH file
      ansible.builtin.lineinfile:
        path: secrets.json
        line:  "{{ lookup('community.hashi_vault.hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault.shujadevops.shop:8200 validate_certs=False') }}"
        create: yes

    - name: create app secret file
      ansible.builtin.lineinfile:
        path: app.json
        line: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=expense-{{env}}/data/{{role_name}} token={{vault_token}} url=https://vault.shujadevops.shop:8200 validate_certs=False') }}"
        create: yes
