- name: Get Secrets
  hosts: localhost
  tasks:
    - name: create  file
      ansible.builtin.lineinfile:
        path: secrets.json
        line:  "{{ lookup('community.hashi_vault.hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault.shujadevops.shop:8200 validate_certs=False') }}"
        create: yes

