- name: Get Secrets
  hosts: localhost
  vars:
    ssh: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault.shujadevops.shop:8200 validate_certs=False') }}"
  tasks:
    - name: create  file
      ansible.builtin.lineinfile:
        path: /tmp/file
        line:  "Username: {{ ssh.user }}"
        create: yes

