  - name: Disable Nodejs
    ansible.builtin.shell: dnf module disable nodejs -y

  - name: Enable nodejs V20
    ansible.builtin.shell: dnf module enable nodejs:20 -y

  - name: Install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: installed

  - name: Copy Service file
    ansible.builtin.copy:
      src: backend.service
      dest: /etc/systemd/system/backend.service

  - name: Adding expense user
    ansible.builtin.user:
      name: expense

  - name: Import app-pre-req task from common role
    ansible.builtin.import_role:
      name: common
      tasks_from: app-pre-req


  - name: Download Nodejs dependencies
    community.general.npm:
      path: /app
      state: present

  - name: Install Python mysql client
    ansible.builtin.pip:
      name:
        - PyMySQL
        - cryptography
      executable: pip3.9

  - name: Load Schema
    community.mysql.mysql_db:
      state: import
      name: all
      target: /app/schema/backend.sql
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql-dev.mohdshuja.com

  - name: Start Backend Service
    ansible.builtin.systemd_service:
      name: backend
      state: restarted
      enabled: yes
      daemon_reload: yes