  - name: Install Nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: Copy expense configuration
    ansible.builtin.template:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: Import app-pre-req task from common role
    ansible.builtin.import_role:
      name: common
      tasks_from: app-pre-req

  - name: Start Nginx
    ansible.builtin.systemd_service:
      name: nginx
      state: restarted
      enabled: yes

  - name: Import newrelic
    ansible.builtin.import_role:
      name: newrelic
      tasks_from: nginx
