  - name: Install Nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: Copy expense configuration
    ansible.builtin.template:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

#  - name: Import app-pre-req task from common role
#    ansible.builtin.import_role:
#      name: common
#      tasks_from: app-pre-req

  - name: Remove old content
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: Creating App dir
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: Downloading and Extracting App content
    ansible.builtin.unarchive:
      src: https://expense-artifacts.s3.amazonaws.com/expense-{{ component }}-v2.zip
      dest: /usr/share/nginx/html
      remote_src: yes


  - name: Start Nginx
    ansible.builtin.systemd_service:
      name: nginx
      state: restarted
      enabled: yes
